# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'swiftui-RealTimeChatApp' do

  use_frameworks!

# Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

# Facebook
pod 'FBSDKLoginKit'

# Google Sign IN
pod 'GoogleSignIn'

end
